### ISSUE TITLE
Instantly access anime on:

### ISSUE THREAD

**Issue by Sheiko222** [blitzprog/animereleasenotifier.com#2]
add http://www.underanime.net/.

**Comment by mrskizzex** [comment]
AFAIK ANR isn't supposed to work in different languages. So this will be most probably never added.

**Comment by blitzprog** [comment]
It wouldn't be too hard to add the basic functionality.
However it's currently not a priority. There are much bigger problems atm and I want to fix those first.
Hope you can understand my point of view :)

**Comment by Sheiko222** [comment]
of course, it is only a recommendation.
